[project]
name = "neuro-eeg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.8",
    "mne>=1.11.0",
    "numpy>=2.2.6",
    "pyedflib>=0.1.42",
    "torch>=2.9.1",
]
